### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by juanjuanya** [lijinke666/lijinke666.github.io#1]
[2/4] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected
version ">=4 <=9". Got "11.12.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

yarn后选完播放器版本就凉凉了，求解惑

**Comment by lijinke666** [comment]
安装什么报错?
什么播放器?
为什么在这个 repo 下 提 issue?

**Comment by juanjuanya** [comment]
就上面的英文啊。提示node版本问题的，是因为我的node版本太新了吗？
音乐播放器应该是
Couldn't find any versions for "react-jinke-music-player" that matches "4.3.4"
? Please choose a version of "react-jinke-music-player" from this list: (Use arr
ow keys)
> 4.3.3
  4.3.2
  4.3.1
  4.3.0
  4.2.3
  4.2.2
  4.2.1
  4.2.0
  4.1.1
  4.1.0
  4.0.4
  4.0.3
  4.0.2
  4.0.1
  4.0.0
  3.5.0
  3.4.2
  3.4.1
  3.4.0
  3.3.2
  3.3.1
  3.3.0
(Move up and down to reveal more choices)

选完后就提示我第一个问题的node版本错误

提issue不是这样提的吗》第一次，经验不足，哈哈，要不我删了？

**Comment by lijinke666** [comment]
首先 我不知道 你clone的哪个项目？
其次 我不知道你为什么要在 这个repo 提  issue？ 你是clone的 `jinke-blog` ?

**Comment by lijinke666** [comment]
这个是两年前的项目了  可能node版本太高了 你 降低一下版本即可
